### ISSUE TITLE
install manjaro first, then install Debian or Ubuntu, the manjaro can't boot 

### ISSUE THREAD

**Issue by nsynet** [manjaro/artwork-gfxboot#2]
Hi all ,

I find the problem 100% occur,install manjaro first, then install Debian or Ubuntu, the manjaro can't boot ,the screen shot is as attached, it seems there is bug here:
![849806833](https://cloud.githubusercontent.com/assets/176097/14856030/f24f68a2-0cc8-11e6-864a-bea8004201fa.jpg)

can anyone check why? Thanks.
nishengyue

**Comment by philmmanjaro** [comment]
Please check your **initrd line**:
```
		initrd /boot/intel-ucode.img /boot/initramfs-4.1-i686.img
		initrd /boot/intel-ucode.img /boot/initramfs-4.1-i686-fallback.img
```
