### ISSUE TITLE
Request: Isolinux customization

### ISSUE THREAD

**Issue by Spatry-CupOfLinux** [manjaro/artwork-gfxboot#3]
Many thanks for the fine efforts you and your team have put into this project. Originally I was going to post this in Manjaro-tools but I felt this section may be more appropriate.

When I change the JPG images in the isolinux folder, my build does not reflect the graphics change. Therefore, I respectfully request that you consider adding the ability to customize the isolinux splash screens or at least provide documentation for end user/developer modification. Thanks again.

-Spatry

**Comment by philmmanjaro** [comment]
Please take a look at the [PKGBUILD](https://github.com/manjaro/packages-extra/blob/master/sonar-isolinux/PKGBUILD) of **sonar-isolinux**. I created a special isolinux package for them. For that I had to create a [fork](https://github.com/manjaro/artwork-gfxboot-sonar). The needed documentation is available, however **manjaro-tools** expects the given packages.

**Comment by philmmanjaro** [comment]
WARNING: All the graphics need to have some special bits set, else GFXBoot will show just black images, fortunately **Kolourpaint** saves the files using exactly the format we need, so in case you run into troubles, open the file with **Kolourpaint**, save it again, and you will have a working image for GFXBoot.
